/* Auto-generated by genmsg_cpp for file /mnt/hgfs/groovy_workspace/sandbox/HoverboardCSCE439/controller/msg/AngularPositionPID.msg */
#ifndef CONTROLLER_MESSAGE_ANGULARPOSITIONPID_H
#define CONTROLLER_MESSAGE_ANGULARPOSITIONPID_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace controller
{
template <class ContainerAllocator>
struct AngularPositionPID_ {
  typedef AngularPositionPID_<ContainerAllocator> Type;

  AngularPositionPID_()
  : header()
  , power(false)
  , x_translation(0.0)
  , y_translation(0.0)
  , lift(0.0)
  , thruster4(0.0)
  , thruster5(0.0)
  {
  }

  AngularPositionPID_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , power(false)
  , x_translation(0.0)
  , y_translation(0.0)
  , lift(0.0)
  , thruster4(0.0)
  , thruster5(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _power_type;
  uint8_t power;

  typedef float _x_translation_type;
  float x_translation;

  typedef float _y_translation_type;
  float y_translation;

  typedef float _lift_type;
  float lift;

  typedef float _thruster4_type;
  float thruster4;

  typedef float _thruster5_type;
  float thruster5;


  typedef boost::shared_ptr< ::controller::AngularPositionPID_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::AngularPositionPID_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct AngularPositionPID
typedef  ::controller::AngularPositionPID_<std::allocator<void> > AngularPositionPID;

typedef boost::shared_ptr< ::controller::AngularPositionPID> AngularPositionPIDPtr;
typedef boost::shared_ptr< ::controller::AngularPositionPID const> AngularPositionPIDConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::controller::AngularPositionPID_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::controller::AngularPositionPID_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::controller::AngularPositionPID_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::controller::AngularPositionPID_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::controller::AngularPositionPID_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d0f1d2a1c6d53a1bb4c2f6ea9cec80f4";
  }

  static const char* value(const  ::controller::AngularPositionPID_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd0f1d2a1c6d53a1bULL;
  static const uint64_t static_value2 = 0xb4c2f6ea9cec80f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::AngularPositionPID_<ContainerAllocator> > {
  static const char* value() 
  {
    return "controller/AngularPositionPID";
  }

  static const char* value(const  ::controller::AngularPositionPID_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::controller::AngularPositionPID_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
bool power\n\
float32 x_translation\n\
float32 y_translation\n\
float32 lift\n\
float32 thruster4\n\
float32 thruster5\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::controller::AngularPositionPID_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::controller::AngularPositionPID_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::controller::AngularPositionPID_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::controller::AngularPositionPID_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.power);
    stream.next(m.x_translation);
    stream.next(m.y_translation);
    stream.next(m.lift);
    stream.next(m.thruster4);
    stream.next(m.thruster5);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AngularPositionPID_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::AngularPositionPID_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::controller::AngularPositionPID_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "power: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.power);
    s << indent << "x_translation: ";
    Printer<float>::stream(s, indent + "  ", v.x_translation);
    s << indent << "y_translation: ";
    Printer<float>::stream(s, indent + "  ", v.y_translation);
    s << indent << "lift: ";
    Printer<float>::stream(s, indent + "  ", v.lift);
    s << indent << "thruster4: ";
    Printer<float>::stream(s, indent + "  ", v.thruster4);
    s << indent << "thruster5: ";
    Printer<float>::stream(s, indent + "  ", v.thruster5);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_ANGULARPOSITIONPID_H

