/* Auto-generated by genmsg_cpp for file /mnt/hgfs/groovy_workspace/sandbox/HoverboardCSCE439/controller/msg/Arbitrator.msg */
#ifndef CONTROLLER_MESSAGE_ARBITRATOR_H
#define CONTROLLER_MESSAGE_ARBITRATOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace controller
{
template <class ContainerAllocator>
struct Arbitrator_ {
  typedef Arbitrator_<ContainerAllocator> Type;

  Arbitrator_()
  : header()
  , power(false)
  , x_translation(0.0)
  , y_translation(0.0)
  , lift(0.0)
  , angle(0.0)
  {
  }

  Arbitrator_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , power(false)
  , x_translation(0.0)
  , y_translation(0.0)
  , lift(0.0)
  , angle(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _power_type;
  uint8_t power;

  typedef float _x_translation_type;
  float x_translation;

  typedef float _y_translation_type;
  float y_translation;

  typedef float _lift_type;
  float lift;

  typedef float _angle_type;
  float angle;


  typedef boost::shared_ptr< ::controller::Arbitrator_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::Arbitrator_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Arbitrator
typedef  ::controller::Arbitrator_<std::allocator<void> > Arbitrator;

typedef boost::shared_ptr< ::controller::Arbitrator> ArbitratorPtr;
typedef boost::shared_ptr< ::controller::Arbitrator const> ArbitratorConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::controller::Arbitrator_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::controller::Arbitrator_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::controller::Arbitrator_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::controller::Arbitrator_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::controller::Arbitrator_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0b428c4a86288a433b08ed71a8350f48";
  }

  static const char* value(const  ::controller::Arbitrator_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0b428c4a86288a43ULL;
  static const uint64_t static_value2 = 0x3b08ed71a8350f48ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::Arbitrator_<ContainerAllocator> > {
  static const char* value() 
  {
    return "controller/Arbitrator";
  }

  static const char* value(const  ::controller::Arbitrator_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::controller::Arbitrator_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
bool power\n\
float32 x_translation\n\
float32 y_translation\n\
float32 lift\n\
float32 angle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::controller::Arbitrator_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::controller::Arbitrator_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::controller::Arbitrator_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::controller::Arbitrator_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.power);
    stream.next(m.x_translation);
    stream.next(m.y_translation);
    stream.next(m.lift);
    stream.next(m.angle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Arbitrator_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::Arbitrator_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::controller::Arbitrator_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "power: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.power);
    s << indent << "x_translation: ";
    Printer<float>::stream(s, indent + "  ", v.x_translation);
    s << indent << "y_translation: ";
    Printer<float>::stream(s, indent + "  ", v.y_translation);
    s << indent << "lift: ";
    Printer<float>::stream(s, indent + "  ", v.lift);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_ARBITRATOR_H

