/* Auto-generated by genmsg_cpp for file /mnt/hgfs/groovy_workspace/sandbox/HoverboardCSCE439/controller/msg/HovercraftControl.msg */
#ifndef CONTROLLER_MESSAGE_HOVERCRAFTCONTROL_H
#define CONTROLLER_MESSAGE_HOVERCRAFTCONTROL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace controller
{
template <class ContainerAllocator>
struct HovercraftControl_ {
  typedef HovercraftControl_<ContainerAllocator> Type;

  HovercraftControl_()
  : header()
  , power(0)
  , rotation(0.0)
  , x_translation(0.0)
  , y_translation(0.0)
  , green_led(0)
  , red_led(0)
  {
  }

  HovercraftControl_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , power(0)
  , rotation(0.0)
  , x_translation(0.0)
  , y_translation(0.0)
  , green_led(0)
  , red_led(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int8_t _power_type;
  int8_t power;

  typedef float _rotation_type;
  float rotation;

  typedef float _x_translation_type;
  float x_translation;

  typedef float _y_translation_type;
  float y_translation;

  typedef int8_t _green_led_type;
  int8_t green_led;

  typedef int8_t _red_led_type;
  int8_t red_led;


  typedef boost::shared_ptr< ::controller::HovercraftControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::HovercraftControl_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct HovercraftControl
typedef  ::controller::HovercraftControl_<std::allocator<void> > HovercraftControl;

typedef boost::shared_ptr< ::controller::HovercraftControl> HovercraftControlPtr;
typedef boost::shared_ptr< ::controller::HovercraftControl const> HovercraftControlConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::controller::HovercraftControl_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::controller::HovercraftControl_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::controller::HovercraftControl_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::controller::HovercraftControl_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::controller::HovercraftControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3e703ba01a482dfbf906246fb0b9dfdf";
  }

  static const char* value(const  ::controller::HovercraftControl_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3e703ba01a482dfbULL;
  static const uint64_t static_value2 = 0xf906246fb0b9dfdfULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::HovercraftControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "controller/HovercraftControl";
  }

  static const char* value(const  ::controller::HovercraftControl_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::controller::HovercraftControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
int8 power\n\
float32 rotation\n\
float32 x_translation\n\
float32 y_translation\n\
int8 green_led\n\
int8 red_led\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::controller::HovercraftControl_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::controller::HovercraftControl_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::controller::HovercraftControl_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::controller::HovercraftControl_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.power);
    stream.next(m.rotation);
    stream.next(m.x_translation);
    stream.next(m.y_translation);
    stream.next(m.green_led);
    stream.next(m.red_led);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HovercraftControl_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::HovercraftControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::controller::HovercraftControl_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "power: ";
    Printer<int8_t>::stream(s, indent + "  ", v.power);
    s << indent << "rotation: ";
    Printer<float>::stream(s, indent + "  ", v.rotation);
    s << indent << "x_translation: ";
    Printer<float>::stream(s, indent + "  ", v.x_translation);
    s << indent << "y_translation: ";
    Printer<float>::stream(s, indent + "  ", v.y_translation);
    s << indent << "green_led: ";
    Printer<int8_t>::stream(s, indent + "  ", v.green_led);
    s << indent << "red_led: ";
    Printer<int8_t>::stream(s, indent + "  ", v.red_led);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_HOVERCRAFTCONTROL_H

